"""Add fraud_decision_audits table.

Revision ID: a1b2c3d4e5f6
Revises: 8f2a4b6c9d1e
Create Date: 2026-06-22 21:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "8f2a4b6c9d1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fraud_decision_audits",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "transaction_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "rules_triggered",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_fraud_decision_audits_transaction_id",
        "fraud_decision_audits",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        "idx_fraud_decision_audits_created_at",
        "fraud_decision_audits",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_fraud_decision_audits_decision",
        "fraud_decision_audits",
        ["decision"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_fraud_decision_audits_decision", table_name="fraud_decision_audits"
    )
    op.drop_index(
        "idx_fraud_decision_audits_created_at", table_name="fraud_decision_audits"
    )
    op.drop_index(
        "idx_fraud_decision_audits_transaction_id",
        table_name="fraud_decision_audits",
    )
    op.drop_table("fraud_decision_audits")
    # ### end Alembic commands ###
